# Demo: NumPy, Pandas
UW Geospatial Data Analysis  
CEE467/CEWA567  
David Shean

modified by Quinn Brencher

## Introduction
This is a quick demo of some key functionality for these core Python packages, emphasizing topics that will help with lab exercises this week and later in the quarter. It is by no means complete! 

Please consult the reading assignment and lists of other excellent, more complete online resources.

## NumPy
> NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a *multidimensional array object*, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

## Pandas
> pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language. 

> pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real-world data analysis in Python. Additionally, it has the broader goal of becoming the most powerful and flexible open source data analysis/manipulation tool available in any language. It is already well on its way toward this goal.

## Matplotlib
>Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python.

>Matplotlib is a Python 2D plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms. Matplotlib can be used in Python scripts, the Python and IPython shells, the Jupyter notebook, web application servers, and four graphical user interface toolkits.

>Matplotlib tries to make easy things easy and hard things possible. You can generate plots, histograms, power spectra, bar charts, errorcharts, scatterplots, etc., with just a few lines of code. For examples, see the sample plots and thumbnail gallery.

>For simple plotting the pyplot module provides a MATLAB-like interface, particularly when combined with IPython. For the power user, you have full control of line styles, font properties, axes properties, etc, via an object oriented interface or via a set of functions familiar to MATLAB users.

## Import necessary modules
* Use shorthand, so you don't have to type out full module name each time
* Note different structure for matplotlib package

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## NumPy 1D array

In [2]:
#Create 1D array of random integers
#Note parenthesis and brackets
a = np.random.randint(0,10,10)
a

array([4, 5, 9, 9, 8, 6, 4, 9, 1, 1])

In [3]:
type(a)

numpy.ndarray

In [4]:
#np.ndarray?

## Constructing an array

In [5]:
#np.array?

In [6]:
np.array(0, 1, 2)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [7]:
#Pass in an array-like object - need brackets around the numbers
np.array([0, 1, 2])

array([0, 1, 2])

In [8]:
mylist = [0, 1, 2]
np.array(mylist)

array([0, 1, 2])

## Array properties and datatypes

In [9]:
a

array([4, 5, 9, 9, 8, 6, 4, 9, 1, 1])

In [10]:
a.shape

(10,)

In [11]:
a.size

10

In [12]:
a.dtype

dtype('int64')

### What is 'int64'?
* Signed integer represented by 64 bits
* Each bit can be 0 or 1
* 0 = 0000000000000000000000000000000000000000000000000000000000000000
* 1 = 0000000000000000000000000000000000000000000000000000000000000001
* 2 = 0000000000000000000000000000000000000000000000000000000000000010
* ...
* https://numpy.org/doc/stable/user/basics.types.html

In [13]:
#Possible unique combinations of 64 bits
int64_range = 2**64
int64_range

18446744073709551616

In [14]:
print(f"{int64_range:.2e}")

1.84e+19


In [15]:
mm = int((2**64)/2)
mm

9223372036854775808

In [16]:
f'A 64-bit signed integer can store values between -{mm} and +{mm-1}'

'A 64-bit signed integer can store values between -9223372036854775808 and +9223372036854775807'

In [17]:
# Overkill for our single integer values
a

array([4, 5, 9, 9, 8, 6, 4, 9, 1, 1])

In [18]:
#Number of bytes (8 bits each) for each element in the array
a.itemsize

8

In [19]:
#Total number of bytes for 10 elements
a.nbytes

80

In [20]:
# Recast to 8-bit unsigned integer (valid range: 0-255)
b = a.astype('uint8')
b

array([4, 5, 9, 9, 8, 6, 4, 9, 1, 1], dtype=uint8)

In [21]:
b.dtype

dtype('uint8')

In [22]:
2**8

256

In [23]:
b

array([4, 5, 9, 9, 8, 6, 4, 9, 1, 1], dtype=uint8)

In [24]:
b.nbytes

10

In [25]:
#Assign value within valid range
b[0] = 255
b

array([255,   5,   9,   9,   8,   6,   4,   9,   1,   1], dtype=uint8)

In [26]:
#Assign value outside of valid range - overlflow!
# https://en.wikipedia.org/wiki/Integer_overflow
b[0] = 257
b

OverflowError: Python integer 257 out of bounds for uint8

## 2D arrays

In [ ]:
a2 = np.random.random((10,10))

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a2.size

In [ ]:
a2.dtype

In [ ]:
#Get first element along first axis
#Question is this first row or col?
a2[0]

In [ ]:
#Get first element along second axis
a2[:,0]

In [ ]:
#Get first element along both axes
a2[0,0]

In [ ]:
#Get slice along first axis - first 3 rows
a2[0:3]

In [ ]:
#Slice along second axis - first 3 cols
a2[:,0:3]

In [ ]:
a2[0:3,0:3]

## ufunc
* Efficiently perform operation element-by-element in "vectorized" fashion (different than GIS vector dataset)
* **Do not loop over arrays** (unless absolutely necessary)
* https://numpy.org/doc/stable/reference/ufuncs.html

In [ ]:
a2 * 10

In [ ]:
# Don't do this!
#for n, i in enumerate(a2):
#    a2[n] = i + 10

In [ ]:
#np.power(a2, 2)
a2**2

In [ ]:
#a2**0.5
np.sqrt(a2)

## Numpy methods
* Operate over entire array, specified axes, or slice
* Very fast/efficient

In [ ]:
a2.mean()

In [ ]:
a2.std()

In [ ]:
a2.min()

In [ ]:
a2

### Note on axis order
* When indexing, first axis (0) will extract rows, second axis (1) will extract cols
* When aggregating (e.g., computing mean along an axis), you are specifing the dimension of the array that will be collapsed, not the dimension that will be returned
    * So axis=0 will aggregate values across all rows for each column in a 2D array

In [ ]:
a2[0:3,0:3]

In [ ]:
a2[0:3,0:3].min(axis=0)

In [ ]:
a2[0:3,0:3].min(axis=1)

## nD arrays

In [ ]:
# how many dimensions can a numpy array have?
# let's try creating arrays with increasingly more dimensions
shape = []
for i in range(100): 
    shape.append(1) # add a new dimension of size 1 to the array shape
    an = np.random.random(shape) # create a random array with the given shape

## Basic array plotting and visualization

In [ ]:
a

In [ ]:
plt.plot(a)

In [ ]:
a2

In [ ]:
plt.plot(a2)

In [ ]:
plt.plot(a2[0])

In [ ]:
#2D array visualization
plt.imshow(a2, cmap='gray')
plt.colorbar()

In [ ]:
plt.hist(a2.ravel(), bins='auto')

## Boolean arrays and fancy indexing

In [ ]:
a2

In [ ]:
a2 > 0.5

In [ ]:
idx = (a2 > 0.5)

In [ ]:
idx

In [ ]:
# Quick visualization, True = yellow (1)
plt.imshow(idx)
plt.colorbar()

In [ ]:
# Return only elements where condition is True
a2[idx]

In [ ]:
# Original shape
a2.shape

In [ ]:
# Selected shape
a2[idx].shape
#idx.nonzero()[0].size

In [ ]:
#Can also be used for assignment
#a2[idx] = 0

In [ ]:
### Bitwise operators, combining boolean arrays

In [ ]:
(a2 > 0.5)

In [ ]:
(a2 < 0.7)

In [ ]:
#Bitwise and - True if both are True
idx = (a2 > 0.5) & (a2 < 0.7)
#Bitwise or - True if either is True
#idx = (a < 0.5) | (a > 0.9)

In [ ]:
idx

In [ ]:
plt.imshow(idx)

In [ ]:
a2[idx]

In [ ]:
a2[idx].shape

In [ ]:
#Invert the boolean array
~idx

In [ ]:
plt.imshow(idx)

In [ ]:
plt.imshow(~idx)

In [ ]:
a2[~idx].shape

## Pandas!

In [ ]:
#pd.DataFrame?

In [ ]:
df = pd.DataFrame(a2)

In [ ]:
df

Wow! Now we have labels for our Numpy array. This will make it much easier to keep track of. 

In [ ]:
df.index = ['a','b','c','d','e','f','g','h','i','j']

In [ ]:
df

In [ ]:
# Still just NumPy array under the hood
df.values

In [ ]:
df.index.values

In [ ]:
# Mean of each column
df.mean()

In [ ]:
# Mean of each row
df.mean(axis=1)

### Reading files with Pandas
Most of the time, you will read in tabular data and let Pandas do the work

In [ ]:
# Path to csv file
csv_fn = './data/GLAH14_tllz_conus_lulcfilt_demfilt.csv'

In [ ]:
pd.read_csv(csv_fn)

In [ ]:
# Store output as a new Pandas DataFrame
glas_df = pd.read_csv(csv_fn)
glas_df

In [ ]:
type(glas_df)

In [ ]:
# For demonstration purpuoses - multiply index to illustrate difference between loc and iloc
glas_df.set_index(glas_df.index*10+1, inplace=True)
glas_df

In [ ]:
# Awesome descriptive statistics for each column
glas_df.describe()

### Indexing and selecting
* https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#different-choices-for-indexing

In [ ]:
# Integer indexing like NumPy
glas_df.iloc[2]

In [ ]:
glas_df.iloc[0:3]

In [ ]:
glas_df.loc[21]

In [ ]:
# Get labeled indices between 0 and 20
glas_df.loc[0:20]

In [ ]:
# Get integer indices between 0 and 20
glas_df.iloc[0:20]

### Selecting columns

In [ ]:
glas_df.columns

In [ ]:
glas_df['glas_z']

In [ ]:
glas_df.glas_z

In [ ]:
glas_df.iloc[:,4]

In [ ]:
glas_df.loc[:,'glas_z']

In [ ]:
#Multiple columns
glas_df['glas_z', 'dem_z']

In [ ]:
# Need to pass in a list of column names
glas_df[['glas_z', 'dem_z']]

In [ ]:
glas_df.loc[:,['glas_z', 'dem_z']]

### Boolean indexing

In [ ]:
glas_df['lulc']

In [ ]:
glas_df['lulc'].value_counts()

In [ ]:
glas_df['lulc'] == 12

In [ ]:
# Boolean Series (index and single column) will be True for records with 'lulc' == 12
idx2 = glas_df['lulc'] == 12

In [ ]:
type(idx2)

In [ ]:
idx2.shape

In [ ]:
glas_df.shape

In [ ]:
# Use to select corresponding rows, returns a new DataFrame with all columns
glas_df[idx2]

In [ ]:
glas_df[idx2].shape

In [ ]:
glas_df[idx2].mean()

### Groupby
* Let's consider statistics for groups of rows that share the same column attribute

In [ ]:
glas_df.groupby('lulc')

In [ ]:
glas_df.groupby('lulc').count()

In [ ]:
glas_df.groupby('lulc').mean()

In [ ]:
glas_df.groupby('lulc').agg(['mean', 'std'])